### ISSUE TITLE
make build_docker error

### ISSUE THREAD

**Issue by sandip761** [mlperf/inference_results_v0.5#19]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-6e88JD/filelock/setup.py'"'"'; __file__='"'"'/tmp/pip-install-6e88JD/filelock/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-6e88JD/filelock/pip-egg-info
         cwd: /tmp/pip-install-6e88JD/filelock/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by psyhtest** [comment]
@sandip761 Which instructions are you trying to follow?

Can you try:
```
$ pip install setuptools --user
```

**Comment by vilmara** [comment]
hi @sandip761. I had the same issue, can you try to edit your docker file and update the below blocks with the commands `python2 -m pip install setuptools` and `python3 -m pip install setuptools`

```
### Install necessary python 2 modules
RUN python2 -m pip install --upgrade pip \
 && python2 -m pip install setuptools \
 && python2 -m pip install --upgrade setuptools wheel virtualenv \
 && python2 -m pip install ez_setup==0.9 \
 && python2 -m pip install numpy \
 && python2 -m pip install absl-py==0.7.1

RUN python3 -m pip install --upgrade pip \
 && python3 -m pip install setuptools \
 && python3 -m pip install --upgrade setuptools wheel virtualenv \
 && python3 -m pip install cmake==3.11.0 \
 && python3 -m pip install pillow==6.0.0 \
 && python3 -m pip install opencv-python-headless
```

**Comment by sandip761** [comment]
Thanks for the help issue reol

> hi @sandip761. I had the same issue, can you try to edit your docker file and update the below blocks with the commands python2 -m pip install setuptools and python3 -m pip install setuptools
> ### Install necessary python 2 modules
> RUN python2 -m pip install --upgrade pip \
>  && python2 -m pip install setuptools \
>  && python2 -m pip install --upgrade setuptools wheel virtualenv \
>  && python2 -m pip install ez_setup==0.9 \
>  && python2 -m pip install numpy \
>  && python2 -m pip install absl-py==0.7.1
> 
> RUN python3 -m pip install --upgrade pip \
>  && python3 -m pip install setuptools \
>  && python3 -m pip install --upgrade setuptools wheel virtualenv \
>  && python3 -m pip install cmake==3.11.0 \
>  && python3 -m pip install pillow==6.0.0 \
>  && python3 -m pip install opencv-python-headless

Thanks for help, Issue resolved.
