### ISSUE TITLE
open cv error while preprocessing

### ISSUE THREAD

**Issue by sandip761** [mlperf/inference_results_v0.5#21]
[2020-02-22 02:49:47,693 preprocess_data.py:80 INFO] Processing image No.0/500...
/work/build/data/imagenet/ILSVRC2012_val_00027145.JPEG
Traceback (most recent call last):
  File "scripts/preprocess_data.py", line 322, in <module>
    main()
  File "scripts/preprocess_data.py", line 313, in main
    preprocessor_map[benchmark](data_dir, output_dir, formats, overwrite, cal_only, val_only)
  File "scripts/preprocess_data.py", line 127, in preprocess_imagenet_for_resnet50
    "data_maps/imagenet/cal_map.txt", ["fp32"], overwrite)
  File "scripts/preprocess_data.py", line 69, in run
    self.convert(image_list)
  File "scripts/preprocess_data.py", line 87, in convert
    image_fp32 = self.loader(os.path.join(self.src_dir, img_file))
  File "scripts/preprocess_data.py", line 110, in loader
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Makefile:183: recipe for target 'preprocess_data' failed
make: *** [preprocess_data] Error 1

**Comment by psyhtest** [comment]
Hmm, some of the images are monochrome. Could this be an issue?

By the way, any idea why are your line numbers slightly off?
```
File "scripts/preprocess_data.py", line 110, in loader
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
```
https://github.com/mlperf/inference_results_v0.5/blob/b2e18edae3dcdf18c95af99837fb97ad9f1a6c0b/closed/NVIDIA/scripts/preprocess_data.py#L108

**Comment by ameyk1** [comment]
Usually this error is if the image did not load properly, check imread function before the line ie. 107 
image = cv2.imread(file)
if I print the file name its imagenet val data. 
In Section : [Download and Pre-Process data](https://github.com/mlperf/inference_results_v0.5/tree/master/closed/NVIDIA#download-and-preprocess-datasets
) of ReadMe suggests that the ImageNet data has to be downloaded separately.

**Comment by psyhtest** [comment]
> In Section : Download and Pre-Process data of ReadMe suggests that the ImageNet data has to be downloaded separately.

Which of course is a problem right now: https://github.com/mlperf/inference/issues/542

**Comment by sandip761** [comment]
> Usually this error is if the image did not load properly, check imread function before the line ie. 107
> image = cv2.imread(file)
> if I print the file name its imagenet val data.
> In Section : Download and Pre-Process data of ReadMe suggests that the ImageNet data has to be downloaded separately.

Thanks for replay

**Comment by sandip761** [comment]
> In Section : Download and Pre-Process data of ReadMe suggests that the ImageNet data has to be downloaded separately.
> 
> Which of course is a problem right now: mlperf/inference#54

Thanks for replay
