### ISSUE TITLE
make build_docker failed with Error 100

### ISSUE THREAD

**Issue by andyluo7** [mlperf/inference_results_v0.5#30]
Step 4/34 : RUN echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/ /" > /etc/apt/sources.list.d/cuda.list  && apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub  && apt-get update  && apt-get install -y --no-install-recommends build-essential autoconf libtool git         curl wget pkg-config sudo ca-certificates vim-tiny automake libssl-dev         bc python3-dev python3-pip python2.7-dev google-perftools gdb libglib2.0-dev clang python-pip sshfs libre2-dev  && apt-get install -y --no-install-recommends cuda-cudart-dev-10-1 cuda-curand-dev-10-1 cuda-nvrtc-dev-10-1 cuda-command-line-tools-10-1 libcublas-dev  && ln -s cuda-10.1 /usr/local/cuda  && apt-get remove -y cmake  && apt-get remove -y libgflags-dev  && apt-get remove -y libprotobuf-dev  && apt-get -y autoremove  && rm -rf /var/lib/apt/lists/*
 ---> Running in 1842a92cb7e7
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.iQ4yspp7Vw/gpg.1.sh --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
gpg: requesting key from 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub'
gpg: key F60F4B3D7FA2AF80: "cudatools <cudatools@nvidia.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Ign:1 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Get:2 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [564 B]
Get:3 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [819 B]
Get:4 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages [254 kB]
Get:5 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists...
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 3h 18min 34s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 3h 19min 36s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 3h 21min 1s). Updates for this repository will not be applied.
The command '/bin/bash -c echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/ /" > /etc/apt/sources.list.d/cuda.list  && apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub  && apt-get update  && apt-get install -y --no-install-recommends build-essential autoconf libtool git         curl wget pkg-config sudo ca-certificates vim-tiny automake libssl-dev         bc python3-dev python3-pip python2.7-dev google-perftools gdb libglib2.0-dev clang python-pip sshfs libre2-dev  && apt-get install -y --no-install-recommends cuda-cudart-dev-10-1 cuda-curand-dev-10-1 cuda-nvrtc-dev-10-1 cuda-command-line-tools-10-1 libcublas-dev  && ln -s cuda-10.1 /usr/local/cuda  && apt-get remove -y cmake  && apt-get remove -y libgflags-dev  && apt-get remove -y libprotobuf-dev  && apt-get -y autoremove  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
Makefile:134: recipe for target 'build_docker' failed
make: *** [build_docker] Error 100

**Comment by nvpohanh** [comment]
```
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 3h 18min 34s). Updates for this repository will not be applied.
```
Looks like a temporary issue? Could you try it again?

**Comment by andyluo7** [comment]
It is the same - 

Step 4/34 : RUN echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/ /" > /etc/apt/sources.list.d/cuda.list  && apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub  && apt-get update  && apt-get install -y --no-install-recommends build-essential autoconf libtool git         curl wget pkg-config sudo ca-certificates vim-tiny automake libssl-dev         bc python3-dev python3-pip python2.7-dev google-perftools gdb libglib2.0-dev clang python-pip sshfs libre2-dev  && apt-get install -y --no-install-recommends cuda-cudart-dev-10-1 cuda-curand-dev-10-1 cuda-nvrtc-dev-10-1 cuda-command-line-tools-10-1 libcublas-dev  && ln -s cuda-10.1 /usr/local/cuda  && apt-get remove -y cmake  && apt-get remove -y libgflags-dev  && apt-get remove -y libprotobuf-dev  && apt-get -y autoremove  && rm -rf /var/lib/apt/lists/*
 ---> Running in 7ad9aaf27fe2
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.pTBjWwoPzc/gpg.1.sh --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
gpg: requesting key from 'http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub'
gpg: key F60F4B3D7FA2AF80: "cudatools <cudatools@nvidia.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Ign:1 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Get:2 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [564 B]
Get:3 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [819 B]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:5 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages [254 kB]
Hit:6 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists...
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 4h 22min 3s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 4h 23min 5s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 4h 24min 29s). Updates for this repository will not be applied.
The command '/bin/bash -c echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/ /" > /etc/apt/sources.list.d/cuda.list  && apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub  && apt-get update  && apt-get install -y --no-install-recommends build-essential autoconf libtool git         curl wget pkg-config sudo ca-certificates vim-tiny automake libssl-dev         bc python3-dev python3-pip python2.7-dev google-perftools gdb libglib2.0-dev clang python-pip sshfs libre2-dev  && apt-get install -y --no-install-recommends cuda-cudart-dev-10-1 cuda-curand-dev-10-1 cuda-nvrtc-dev-10-1 cuda-command-line-tools-10-1 libcublas-dev  && ln -s cuda-10.1 /usr/local/cuda  && apt-get remove -y cmake  && apt-get remove -y libgflags-dev  && apt-get remove -y libprotobuf-dev  && apt-get -y autoremove  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
Makefile:134: recipe for target 'build_docker' failed
make: *** [build_docker] Error 100

**Comment by nvpohanh** [comment]
@andyluo7 Could you reset your system clock time? 
References:
https://blog.sleeplessbeastie.eu/2019/11/15/how-to-deal-with-repository-is-not-valid-yet-error/
https://askubuntu.com/questions/1059217/getting-release-is-not-valid-yet-while-updating-ubuntu-docker-container

**Comment by andyluo7** [comment]
@nvpohanh resetting system clock time works. Thanks.
