### ISSUE TITLE
Docker build error 

### ISSUE THREAD

**Issue by andyluo7** [mlperf/inference_results_v0.5#31]
Selecting previously unselected package graphsurgeon-tf.
(Reading database ... 21872 files and directories currently installed.)
Preparing to unpack .../graphsurgeon-tf_6.0.1-1+cuda10.1_amd64.deb ...
Unpacking graphsurgeon-tf (6.0.1-1+cuda10.1) ...
Selecting previously unselected package uff-converter-tf.
Preparing to unpack .../uff-converter-tf_6.0.1-1+cuda10.1_amd64.deb ...
Unpacking uff-converter-tf (6.0.1-1+cuda10.1) ...
Setting up graphsurgeon-tf (6.0.1-1+cuda10.1) ...
Setting up uff-converter-tf (6.0.1-1+cuda10.1) ...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/uff/__init__.py", line 1, in <module>
    from uff import converters, model  # noqa
  File "/usr/lib/python2.7/dist-packages/uff/model/__init__.py", line 1, in <module>
    from . import uff_pb2 as uff_pb  # noqa
  File "/usr/lib/python2.7/dist-packages/uff/model/uff_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal
chmod: cannot access '/bin/convert_to_uff.py': No such file or directory
Removing intermediate container d562cfcc0821
 ---> 5fec2f27ce06
Step 29/34 : RUN echo 'deb http://archive.ubuntu.com/ubuntu disco main restricted universe multiverse' | tee -a /etc/apt/sources.list.d/disco.list   && echo 'Package: *\nPin: release a=disco\nPin-Priority: -10\n' | tee -a /etc/apt/preferences.d/disco.pref   && apt-get update   && apt-get install --no-install-recommends -t disco -y libjemalloc2 libtcmalloc-minimal4
 ---> Running in 9857577f1932
deb http://archive.ubuntu.com/ubuntu disco main restricted universe multiverse
Package: *\nPin: release a=disco\nPin-Priority: -10\n
Ign:1 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [564 B]
Get:4 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [819 B]
Get:5 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:6 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages [254 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [52.4 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [908 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [843 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [8505 B]
Ign:13 http://archive.ubuntu.com/ubuntu disco InRelease
Get:14 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Err:18 http://archive.ubuntu.com/ubuntu disco Release
  404  Not Found [IP: 91.189.88.152 80]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1205 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [19.8 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [66.8 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1376 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [8286 B]
Get:24 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [7671 B]
Reading package lists...
E: The repository 'http://archive.ubuntu.com/ubuntu disco Release' does not have a Release file.
The command '/bin/bash -c echo 'deb http://archive.ubuntu.com/ubuntu disco main restricted universe multiverse' | tee -a /etc/apt/sources.list.d/disco.list   && echo 'Package: *\nPin: release a=disco\nPin-Priority: -10\n' | tee -a /etc/apt/preferences.d/disco.pref   && apt-get update   && apt-get install --no-install-recommends -t disco -y libjemalloc2 libtcmalloc-minimal4' returned a non-zero code: 100
Makefile:134: recipe for target 'build_docker' failed
make: *** [build_docker] Error 100

**Comment by nvpohanh** [comment]
@andyluo7 Please replace all the `disco` to `eoan`

Original:
```
# Install libjemalloc2
RUN echo 'deb http://archive.ubuntu.com/ubuntu disco main restricted universe multiverse' | tee -a /etc/apt/sources.list.d/disco.list \
  && echo 'Package: *\nPin: release a=disco\nPin-Priority: -10\n' | tee -a /etc/apt/preferences.d/disco.pref \
  && apt-get update \
  && apt-get install --no-install-recommends -t disco -y libjemalloc2 libtcmalloc-minimal4
```
New:
```
# Install libjemalloc2
RUN echo 'deb http://archive.ubuntu.com/ubuntu eoan main restricted universe multiverse' | tee -a /etc/apt/sources.list.d/eoan.list \
  && echo 'Package: *\nPin: release a=eoan\nPin-Priority: -10\n' | tee -a /etc/apt/preferences.d/eoan.pref \
  && apt-get update \
  && apt-get install --no-install-recommends -t eoan -y libjemalloc2 libtcmalloc-minimal4

```

**Comment by andyluo7** [comment]
It works. Thanks!
