### ISSUE TITLE
make build_docker failed with Error 100

### ISSUE THREAD

**Issue by alanshao023** [mlperf/inference_results_v0.5#37]
Step 29/34 : RUN echo 'deb http://archive.ubuntu.com/ubuntu disco main restricted universe multiverse' | tee -a /etc/apt/sources.list.d/disco.list   && echo 'Package: *\nPin: release a=disco\nPin-Priority: -10\n' | tee -a /etc/apt/preferences.d/disco.pref   && apt-get update   && apt-get install --no-install-recommends -t disco -y libjemalloc2 libtcmalloc-minimal4
 ---> Running in 660be38d0a05
deb http://archive.ubuntu.com/ubuntu disco main restricted universe multiverse
Package: *\nPin: release a=disco\nPin-Priority: -10\n
Ign:1 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Get:2 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release [697 B]
Get:3 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release.gpg [836 B]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:5 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
Get:5 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages [326 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [9834 B]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [890 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [101 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [1043 kB]
Get:11 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Ign:13 http://archive.ubuntu.com/ubuntu disco InRelease
Get:14 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Err:18 http://archive.ubuntu.com/ubuntu disco Release
  404  Not Found [IP: 91.189.88.152 80]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [117 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [27.4 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1341 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1417 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [8432 B]
Get:24 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [8286 B]
Reading package lists...
E: The repository 'http://archive.ubuntu.com/ubuntu disco Release' does not have a Release file.
The command '/bin/bash -c echo 'deb http://archive.ubuntu.com/ubuntu disco main restricted universe multiverse' | tee -a /etc/apt/sources.list.d/disco.list   && echo 'Package: *\nPin: release a=disco\nPin-Priority: -10\n' | tee -a /etc/apt/preferences.d/disco.pref   && apt-get update   && apt-get install --no-install-recommends -t disco -y libjemalloc2 libtcmalloc-minimal4' returned a non-zero code: 100
Makefile:134: recipe for target 'build_docker' failed
make: *** [build_docker] Error 100

**Comment by nvpohanh** [comment]
Please find the fix here: https://github.com/mlperf/inference_results_v0.5/issues/31#issuecomment-622079116

**Comment by alanshao023** [comment]
It works! By the way I'm using CentOS 7.8. Thanks.
