### ISSUE TITLE
T4 performance is limited

### ISSUE THREAD

**Issue by jimmy135769** [mlperf/inference_results_v0.5#39]
I use a T4 to test and set Target_qps to 59704 and 7463,  but I get the same Samples per second.

**Target_qps : 59704**
================================================
MLPerf Results Summary
================================================
SUT name : LWIS_Server
Scenario : Offline
Mode     : Performance
Samples per second: 1299.33
Result is : VALID
  Min duration satisfied : Yes
  Min queries satisfied : Yes

================================================
Additional Stats
================================================
Min latency (ns)                : 144802822
Max latency (ns)                : 3032687356556
Mean latency (ns)               : 1516419298170
50.00 percentile latency (ns)   : 1516424815055
90.00 percentile latency (ns)   : 2729485045180
95.00 percentile latency (ns)   : 2881092314727
97.00 percentile latency (ns)   : 2941774368763
99.00 percentile latency (ns)   : 3002456357383
99.90 percentile latency (ns)   : 3029742804377

================================================
Test Parameters Used
================================================
samples_per_query : 3940464
target_qps : 59704
target_latency (ns): 0
max_async_queries : 1
min_duration (ms): 60000
max_duration (ms): 0
min_query_count : 1
max_query_count : 0
qsl_rng_seed : 3133965575612453542
sample_index_rng_seed : 665484352860916858
schedule_rng_seed : 3622009729038561421
accuracy_log_rng_seed : 0
accuracy_log_probability : 0
print_timestamps : false
performance_issue_unique : false
performance_issue_same : false
performance_issue_same_index : 0
performance_sample_count : 256

No warnings encountered during test.

1 ERROR encountered. See detailed log.

**Target_qps : 7463**
================================================
MLPerf Results Summary
================================================
SUT name : LWIS_Server
Scenario : Offline
Mode     : Performance
Samples per second: 1299.71
Result is : VALID
  Min duration satisfied : Yes
  Min queries satisfied : Yes

================================================
Additional Stats
================================================
Min latency (ns)                : 106632381
Max latency (ns)                : 378973996050
Mean latency (ns)               : 189538565727
50.00 percentile latency (ns)   : 189582619865
90.00 percentile latency (ns)   : 341143686790
95.00 percentile latency (ns)   : 360051167872
97.00 percentile latency (ns)   : 367633847544
99.00 percentile latency (ns)   : 375217777389
99.90 percentile latency (ns)   : 378664180274

================================================
Test Parameters Used
================================================
samples_per_query : 492558
target_qps : 7463
target_latency (ns): 0
max_async_queries : 1
min_duration (ms): 60000
max_duration (ms): 0
min_query_count : 1
max_query_count : 0
qsl_rng_seed : 3133965575612453542
sample_index_rng_seed : 665484352860916858
schedule_rng_seed : 3622009729038561421
accuracy_log_rng_seed : 0
accuracy_log_probability : 0
print_timestamps : false
performance_issue_unique : false
performance_issue_same : false
performance_issue_same_index : 0
performance_sample_count : 256

No warnings encountered during test.

1 ERROR encountered. See detailed log.

What is the problem? thanks

**Comment by nvpohanh** [comment]
Which benchmark is this? Does the T4 have good cooling? You can monitor GPU temperature by `nvidia-smi dmon -s pc`. Thanks

**Comment by jimmy135769** [comment]
I use version v0.5 benchmark on SSD-small and the foundation is NVIDIA-Optimized Implementations

GPU temperature maintenance 53°C

# gpu   pwr gtemp mtemp  mclk  pclk
# Idx     W     C     C   MHz   MHz
      0    38    53     -  5000   146
      0    41    53     -  5000   146
      0    40    53     -  5000   146
      0    38    53     -  5000   146
      0    38    53     -  5000   146
      0    40    53     -  5000   146
      0    41    53     -  5000   146


I have observed that the latency increases a lot in Log Contention Counters part both Target_qps 59704 and 7463.


**Target_qps : 59704**

"pid": 15053, "tid": 15053, "ts": 8595ns : LoadgenVersionInfo:
"pid": 15053, "tid": 15053, "ts": 8595ns : version : .5a1 @ 61220457de
"pid": 15053, "tid": 15053, "ts": 8595ns : build_date_local : 2020-08-18T02:06:24.165751
"pid": 15053, "tid": 15053, "ts": 8595ns : build_date_utc   : 2020-08-18T02:06:24.165758
"pid": 15053, "tid": 15053, "ts": 8595ns : git_commit_date  : 2019-10-01T10:39:03-07:00
"pid": 15053, "tid": 15053, "ts": 8595ns : git_log :

61220457dec221ed1984c62bd9d382698bd71bc6 loadgen: re-apply fix for msvc (#459)
5684c11e3987b614aae830390fa0e92f56b7e800 Update the broken txt url link (#456)
55c0ea4e772634107f3e67a6d0da61e6a2ca390d https://github.com/mlperf/inference/issues/450 logging per-sample info regardless of scenario (#454)
d31c18fbd9854a4f1c489ca1bc4cd818e48f2bc5 Adding a flag to accuracy-coco script which fixes issue with preprocessing that removes 48 empty images (#453)
1d0e06e54a7d763cf228bdfd8b1e987976e4222f Implement LogSettings::enable_trace (#466)
d9c4b77ed961c20bdff2b2a4c7d0904a91408882 Merge pull request #467 from guschmue/gs/config-fix
62eddd5fa123c0ed7f230868cf7e6d08f49f697c there was a dot missing when parsing items from config file
5c4c571583ebf9703daeadd5a5f90f6bd0253852  Offline scenario PerformanceOnly mode should generate 1 instead of 2 queries (#461)
6019b1b6154f6fe399519743cd59394554d80d26 Update README.md
2e9a1f7c164ec715a6cbd014eea805d69b4b14a4 Merge pull request #427 from nvmbreughe/master
ace74c303888e575826d2a8be8460608d156efae Merge pull request #406 from guschmue/gs/fix-no-results
52699022d32271a00c7ec840acb77180a8c5d061 Split on any whitespace in val_map.txt, not just tab. (#458)
5a4803e37b990c0f294c8a7caa6029fb6f201573 On MacOS/LLVM thread_ids are not auto-convertible to uint64_t and have to be converted manually (#439)
94e7f492ff936e02a626c49918fd8b17d076fe7e Merge pull request #449 from guschmue/gs/fix-docker
2dd8318b3f7a6ffea49d88716b96cb3172e66834 fix output path in docker image
4df4601374cfc2c2c6d25b8aef08585614a8f5cd Merge pull request #432 from guschmue/gs/fix-target-qps

"pid": 15053, "tid": 15053, "ts": 8595ns : git_status :



"pid": 15053, "tid": 15053, "ts": 8595ns : SHA1 of files :

012aad77e5206c89d50718c46c119d1f3cb056b2 /.clang-format
a3355ff8f163cabbf26adb86d3aa0e5da72900c7 /BUILD.gn
25ddf9bbe1429de0d036f073497c1e90cb419519 /CMakeLists.txt
79fbce4843967690e0750fd7ffc021f4f1e4c5c4 /README.md
34b89a712a0ca1691b89715fe2ce459a676d0f77 /README_BUILD.md
f75741b91085a20ebb23de1ce03d45a56d3457fe /README_FAQ.md
fa2add871dc7440cbda1f8c7a69e96eb6499951a /bindings/c_api.cc
8fdaa27778cf3ee2eb85d5b7040e8ddfcab68108 /bindings/c_api.h
9c778599614f2a42cb95ad662213cde5fcf791ec /bindings/python_api.cc
4b68d3399b31e14e554cff678a0db9b4d1299e23 /demos/BUILD.gn
07d85ea5fefade8d3d66ca832b783bf90e5bce7d /demos/py_demo_multi_stream.py
2f941e949770a2ea9ad6d6eea2f33fc19150edcd /demos/py_demo_multi_stream_free.py
73c60cf12cfb69619249e637f9bcad18a47cda6c /demos/py_demo_offline.py
02a6ddbe8b51bde2cfed32abeccdb7fdd9cfe4e7 /demos/py_demo_server.py
3e7d786882099ac784bf878f1cde9dd3db2f6d9f /demos/py_demo_single_stream.py
19242fc8e0f9e3eaf8bec9964ba33d760eeade96 /loadgen.cc
5526ae8ce9547a95f10e1ac465056bfba2fccb47 /loadgen.h
47f748307536f80cfc606947b440dd732afc2637 /loadgen_integration_diagram.svg
a69511f0c916eb2100b7f665605ff6ffdf0546be /logging.cc
fdb61b8a2e2593bab4ae5bf9758434cf6a60e218 /logging.h
a879f127c4bb64d131056942734ea1a6ba9c3033 /query_sample.h
922acb63aa734d36e3fa34d87ff0f361052e0c51 /query_sample_library.h
369f4320e027fc276d2519021696c7d1027b7320 /setup.py
744482c84336420adbbe31ef8c2b39612c6ca3f8 /system_under_test.h
ad3fa5b4e0395e77cd5e00ebae2d0a0eb538969d /test_settings.h
2f6e9b9506486cd0de01b8d8f5f0dfe8a8878773 /test_settings_internal.cc
1c15731be5abc26a6c90356720146862da7c22b4 /test_settings_internal.h
86fc4c8035e7b73132c56d1781aca647b6bd6916 /utils.cc
5395a04f82e90288f52bf918d7b1d6027bfe0964 /utils.h
e1c46896da912ff2a0187276c3a8ba4eec057a17 /version.cc
9d574baa64424e9c708fcfedd3dbb0b518a65fcc /version.h
07dbee77c9707efdb95def65477c288fe6667e92 /version_generator.py

"pid": 15053, "tid": 15053, "ts": 20705ns : Date + time of test: 2020-08-26T02:38:55Z
"pid": 15053, "tid": 15053, "ts": 20705ns : System Under Test (SUT) name: LWIS_Server
"pid": 15053, "tid": 15053, "ts": 20705ns : Query Sample Library (QSL) name: LWIS_SampleLibrary
"pid": 15053, "tid": 15053, "ts": 20705ns : QSL total size: 5000
"pid": 15053, "tid": 15053, "ts": 20705ns : QSL performance size*: 256
"pid": 15053, "tid": 15053, "ts": 20705ns : *TestSettings (performance_sample_count_override) can override
"pid": 15053, "tid": 15053, "ts": 20705ns : *Refer to Effective Settings for actual value
"pid": 15053, "tid": 15053, "ts": 26012ns : 
"pid": 15053, "tid": 15053, "ts": 26012ns : Effective Settings:
"pid": 15053, "tid": 15053, "ts": 26012ns : Scenario : Offline
"pid": 15053, "tid": 15053, "ts": 26012ns : Test mode : Performance
"pid": 15053, "tid": 15053, "ts": 26012ns : samples_per_query : 3940464
"pid": 15053, "tid": 15053, "ts": 26012ns : target_qps : 59704
"pid": 15053, "tid": 15053, "ts": 26012ns : target_latency (ns): 0
"pid": 15053, "tid": 15053, "ts": 26012ns : target_latency_percentile : 4.64176e-310
"pid": 15053, "tid": 15053, "ts": 26012ns : max_async_queries : 1
"pid": 15053, "tid": 15053, "ts": 26012ns : target_duration (ms): 0
"pid": 15053, "tid": 15053, "ts": 26012ns : min_duration (ms): 60000
"pid": 15053, "tid": 15053, "ts": 26012ns : max_duration (ms): 0
"pid": 15053, "tid": 15053, "ts": 26012ns : min_query_count : 1
"pid": 15053, "tid": 15053, "ts": 26012ns : max_query_count : 0
"pid": 15053, "tid": 15053, "ts": 26012ns : min_sample_count : 3940464
"pid": 15053, "tid": 15053, "ts": 26012ns : qsl_rng_seed : 3133965575612453542
"pid": 15053, "tid": 15053, "ts": 26012ns : sample_index_rng_seed : 665484352860916858
"pid": 15053, "tid": 15053, "ts": 26012ns : schedule_rng_seed : 3622009729038561421
"pid": 15053, "tid": 15053, "ts": 26012ns : accuracy_log_rng_seed : 0
"pid": 15053, "tid": 15053, "ts": 26012ns : accuracy_log_probability : 0
"pid": 15053, "tid": 15053, "ts": 26012ns : print_timestamps : false
"pid": 15053, "tid": 15053, "ts": 26012ns : performance_issue_unique : false
"pid": 15053, "tid": 15053, "ts": 26012ns : performance_issue_same : false
"pid": 15053, "tid": 15053, "ts": 26012ns : performance_issue_same_index : 0
"pid": 15053, "tid": 15053, "ts": 26012ns : performance_sample_count : 256
"pid": 15053, "tid": 15053, "ts": 27862ns : 
"pid": 15053, "tid": 15053, "ts": 27862ns : Requested Settings:
"pid": 15053, "tid": 15053, "ts": 27862ns : Scenario : Offline
"pid": 15053, "tid": 15053, "ts": 27862ns : Test mode : Performance
"pid": 15053, "tid": 15053, "ts": 27862ns : offline_expected_qps : 59704
"pid": 15053, "tid": 15053, "ts": 27862ns : min_duration_ms : 60000
"pid": 15053, "tid": 15053, "ts": 27862ns : max_duration_ms : 0
"pid": 15053, "tid": 15053, "ts": 27862ns : min_query_count : 1
"pid": 15053, "tid": 15053, "ts": 27862ns : max_query_count : 0
"pid": 15053, "tid": 15053, "ts": 27862ns : qsl_rng_seed : 3133965575612453542
"pid": 15053, "tid": 15053, "ts": 27862ns : sample_index_rng_seed : 665484352860916858
"pid": 15053, "tid": 15053, "ts": 27862ns : schedule_rng_seed : 3622009729038561421
"pid": 15053, "tid": 15053, "ts": 27862ns : accuracy_log_rng_seed : 0
"pid": 15053, "tid": 15053, "ts": 27862ns : accuracy_log_probability : 0
"pid": 15053, "tid": 15053, "ts": 27862ns : print_timestamps : false
"pid": 15053, "tid": 15053, "ts": 27862ns : performance_issue_unique : false
"pid": 15053, "tid": 15053, "ts": 27862ns : performance_issue_same : false
"pid": 15053, "tid": 15053, "ts": 27862ns : performance_issue_same_index : 0
"pid": 15053, "tid": 15053, "ts": 27862ns : performance_sample_count_override : 0
"pid": 15053, "tid": 15053, "ts": 27862ns : 
"pid": 15053, "tid": 15053, "ts": 29855ns : Starting performance mode:
"pid": 15053, "tid": 15053, "ts": 176676ns : Loading QSL : "set" : "[1873,183,1526,701,1720,1110,1423,4759,1487,1163,4702,2782,998,141,2734,2005,309,4626,2571,4925,994,4800,561,3565,242,261,1636,2115,3559,3941,4128,4080,1032,2807,3332,732,1569,4497,4323,1380,2384,4048,654,4001,3923,1287,638,4243,634,1100,3934,3449,4983,78,243,1729,3621,4175,3742,4886,3064,2001,2849,4316,3114,2286,4355,2017,2,1076,1974,166,28,12,1453,2453,1718,2932,859,1854,4701,1540,976,1271,3197,4637,3640,1716,2165,4348,893,3606,3813,3527,2233,2482,80,2348,4321,4242,2365,4996,1436,3482,4584,4342,4864,278,3553,1921,2073,4745,3062,4332,1961,1530,4057,1838,2308,1705,1927,1783,4770,397,1345,3861,3698,2686,4486,2832,907,4503,735,3784,1724,3858,3433,4309,630,1508,3576,673,4253,2775,1275,984,700,750,494,4356,1193,3842,1077,2491,2873,3218,3921,4027,3799,1412,3848,435,3917,593,1440,1334,49,4616,2318,3533,4295,4757,3254,584,234,341,2928,1762,3879,2260,2059,4923,2120,679,13,3699,1266,4326,465,4082,3899,481,1601,351,4913,3885,4907,4311,4905,368,273,3907,3315,2603,3607,887,3993,1954,1659,3880,81,3968,3059,1101,1335,2203,2812,823,3625,3725,1324,965,1162,4418,2911,452,1772,4706,1694,3632,2856,843,2102,3004,3267,4548,1622,3350,4703,697,4113,3287,1685,4624,4965,3529,1658,3439,1030,4476,4051,598,4536,3414,1273,2406]"
"pid": 15053, "tid": 15053, "ts": 205474652ns : GeneratedQueries: "queries" : 1, "samples per query" : 3940464, "duration" : 16749
"pid": 15053, "tid": 15053, "ts": 248938745ns : ERROR : Ending early: Ran out of generated queries to issue before the minimum query count and test duration were reached.
"pid": 15053, "tid": 15053, "ts": 248938745ns : Please update the relevant expected latency or target qps in the TestSettings so they are more accurate.
"pid": 15053, "tid": 15053, "ts": 3032916199681ns : Log Contention Counters:
"pid": 15053, "tid": 15053, "ts": 3032916199681ns : 0 : swap_request_slots_retry_count
"pid": 15053, "tid": 15053, "ts": 3032916199681ns : 0 : swap_request_slots_retry_retry_count
"pid": 15053, "tid": 15053, "ts": 3032916199681ns : 0 : swap_request_slots_retry_reencounter_count
"pid": 15053, "tid": 15053, "ts": 3032916199681ns : 0 : start_reading_entries_retry_count
"pid": 15053, "tid": 15053, "ts": 3032916199681ns : 0 : tls_total_log_cas_fail_count
"pid": 15053, "tid": 15053, "ts": 3032916199681ns : 0 : tls_total_swap_buffers_slot_retry_count
"pid": 15053, "tid": 15053, "ts": 3032916202770ns : POWER_BEGIN: "mode" : Performance, "time" : 08-26-2020 02:38:55.673
"pid": 15053, "tid": 15053, "ts": 3032916202770ns : POWER_END: "mode" : Performance, "time" : 08-26-2020 03:29:28.361


**Target_qps : 7463**

"pid": 2368, "tid": 2368, "ts": 8187ns : LoadgenVersionInfo:
"pid": 2368, "tid": 2368, "ts": 8187ns : version : .5a1 @ 61220457de
"pid": 2368, "tid": 2368, "ts": 8187ns : build_date_local : 2020-08-18T02:06:24.165751
"pid": 2368, "tid": 2368, "ts": 8187ns : build_date_utc   : 2020-08-18T02:06:24.165758
"pid": 2368, "tid": 2368, "ts": 8187ns : git_commit_date  : 2019-10-01T10:39:03-07:00
"pid": 2368, "tid": 2368, "ts": 8187ns : git_log :

61220457dec221ed1984c62bd9d382698bd71bc6 loadgen: re-apply fix for msvc (#459)
5684c11e3987b614aae830390fa0e92f56b7e800 Update the broken txt url link (#456)
55c0ea4e772634107f3e67a6d0da61e6a2ca390d https://github.com/mlperf/inference/issues/450 logging per-sample info regardless of scenario (#454)
d31c18fbd9854a4f1c489ca1bc4cd818e48f2bc5 Adding a flag to accuracy-coco script which fixes issue with preprocessing that removes 48 empty images (#453)
1d0e06e54a7d763cf228bdfd8b1e987976e4222f Implement LogSettings::enable_trace (#466)
d9c4b77ed961c20bdff2b2a4c7d0904a91408882 Merge pull request #467 from guschmue/gs/config-fix
62eddd5fa123c0ed7f230868cf7e6d08f49f697c there was a dot missing when parsing items from config file
5c4c571583ebf9703daeadd5a5f90f6bd0253852  Offline scenario PerformanceOnly mode should generate 1 instead of 2 queries (#461)
6019b1b6154f6fe399519743cd59394554d80d26 Update README.md
2e9a1f7c164ec715a6cbd014eea805d69b4b14a4 Merge pull request #427 from nvmbreughe/master
ace74c303888e575826d2a8be8460608d156efae Merge pull request #406 from guschmue/gs/fix-no-results
52699022d32271a00c7ec840acb77180a8c5d061 Split on any whitespace in val_map.txt, not just tab. (#458)
5a4803e37b990c0f294c8a7caa6029fb6f201573 On MacOS/LLVM thread_ids are not auto-convertible to uint64_t and have to be converted manually (#439)
94e7f492ff936e02a626c49918fd8b17d076fe7e Merge pull request #449 from guschmue/gs/fix-docker
2dd8318b3f7a6ffea49d88716b96cb3172e66834 fix output path in docker image
4df4601374cfc2c2c6d25b8aef08585614a8f5cd Merge pull request #432 from guschmue/gs/fix-target-qps

"pid": 2368, "tid": 2368, "ts": 8187ns : git_status :



"pid": 2368, "tid": 2368, "ts": 8187ns : SHA1 of files :

012aad77e5206c89d50718c46c119d1f3cb056b2 /.clang-format
a3355ff8f163cabbf26adb86d3aa0e5da72900c7 /BUILD.gn
25ddf9bbe1429de0d036f073497c1e90cb419519 /CMakeLists.txt
79fbce4843967690e0750fd7ffc021f4f1e4c5c4 /README.md
34b89a712a0ca1691b89715fe2ce459a676d0f77 /README_BUILD.md
f75741b91085a20ebb23de1ce03d45a56d3457fe /README_FAQ.md
fa2add871dc7440cbda1f8c7a69e96eb6499951a /bindings/c_api.cc
8fdaa27778cf3ee2eb85d5b7040e8ddfcab68108 /bindings/c_api.h
9c778599614f2a42cb95ad662213cde5fcf791ec /bindings/python_api.cc
4b68d3399b31e14e554cff678a0db9b4d1299e23 /demos/BUILD.gn
07d85ea5fefade8d3d66ca832b783bf90e5bce7d /demos/py_demo_multi_stream.py
2f941e949770a2ea9ad6d6eea2f33fc19150edcd /demos/py_demo_multi_stream_free.py
73c60cf12cfb69619249e637f9bcad18a47cda6c /demos/py_demo_offline.py
02a6ddbe8b51bde2cfed32abeccdb7fdd9cfe4e7 /demos/py_demo_server.py
3e7d786882099ac784bf878f1cde9dd3db2f6d9f /demos/py_demo_single_stream.py
19242fc8e0f9e3eaf8bec9964ba33d760eeade96 /loadgen.cc
5526ae8ce9547a95f10e1ac465056bfba2fccb47 /loadgen.h
47f748307536f80cfc606947b440dd732afc2637 /loadgen_integration_diagram.svg
a69511f0c916eb2100b7f665605ff6ffdf0546be /logging.cc
fdb61b8a2e2593bab4ae5bf9758434cf6a60e218 /logging.h
a879f127c4bb64d131056942734ea1a6ba9c3033 /query_sample.h
922acb63aa734d36e3fa34d87ff0f361052e0c51 /query_sample_library.h
369f4320e027fc276d2519021696c7d1027b7320 /setup.py
744482c84336420adbbe31ef8c2b39612c6ca3f8 /system_under_test.h
ad3fa5b4e0395e77cd5e00ebae2d0a0eb538969d /test_settings.h
2f6e9b9506486cd0de01b8d8f5f0dfe8a8878773 /test_settings_internal.cc
1c15731be5abc26a6c90356720146862da7c22b4 /test_settings_internal.h
86fc4c8035e7b73132c56d1781aca647b6bd6916 /utils.cc
5395a04f82e90288f52bf918d7b1d6027bfe0964 /utils.h
e1c46896da912ff2a0187276c3a8ba4eec057a17 /version.cc
9d574baa64424e9c708fcfedd3dbb0b518a65fcc /version.h
07dbee77c9707efdb95def65477c288fe6667e92 /version_generator.py

"pid": 2368, "tid": 2368, "ts": 19929ns : Date + time of test: 2020-08-27T02:29:31Z
"pid": 2368, "tid": 2368, "ts": 19929ns : System Under Test (SUT) name: LWIS_Server
"pid": 2368, "tid": 2368, "ts": 19929ns : Query Sample Library (QSL) name: LWIS_SampleLibrary
"pid": 2368, "tid": 2368, "ts": 19929ns : QSL total size: 5000
"pid": 2368, "tid": 2368, "ts": 19929ns : QSL performance size*: 256
"pid": 2368, "tid": 2368, "ts": 19929ns : *TestSettings (performance_sample_count_override) can override
"pid": 2368, "tid": 2368, "ts": 19929ns : *Refer to Effective Settings for actual value
"pid": 2368, "tid": 2368, "ts": 25819ns : 
"pid": 2368, "tid": 2368, "ts": 25819ns : Effective Settings:
"pid": 2368, "tid": 2368, "ts": 25819ns : Scenario : Offline
"pid": 2368, "tid": 2368, "ts": 25819ns : Test mode : Performance
"pid": 2368, "tid": 2368, "ts": 25819ns : samples_per_query : 492558
"pid": 2368, "tid": 2368, "ts": 25819ns : target_qps : 7463
"pid": 2368, "tid": 2368, "ts": 25819ns : target_latency (ns): 0
"pid": 2368, "tid": 2368, "ts": 25819ns : target_latency_percentile : 4.65167e-310
"pid": 2368, "tid": 2368, "ts": 25819ns : max_async_queries : 1
"pid": 2368, "tid": 2368, "ts": 25819ns : target_duration (ms): 0
"pid": 2368, "tid": 2368, "ts": 25819ns : min_duration (ms): 60000
"pid": 2368, "tid": 2368, "ts": 25819ns : max_duration (ms): 0
"pid": 2368, "tid": 2368, "ts": 25819ns : min_query_count : 1
"pid": 2368, "tid": 2368, "ts": 25819ns : max_query_count : 0
"pid": 2368, "tid": 2368, "ts": 25819ns : min_sample_count : 492558
"pid": 2368, "tid": 2368, "ts": 25819ns : qsl_rng_seed : 3133965575612453542
"pid": 2368, "tid": 2368, "ts": 25819ns : sample_index_rng_seed : 665484352860916858
"pid": 2368, "tid": 2368, "ts": 25819ns : schedule_rng_seed : 3622009729038561421
"pid": 2368, "tid": 2368, "ts": 25819ns : accuracy_log_rng_seed : 0
"pid": 2368, "tid": 2368, "ts": 25819ns : accuracy_log_probability : 0
"pid": 2368, "tid": 2368, "ts": 25819ns : print_timestamps : false
"pid": 2368, "tid": 2368, "ts": 25819ns : performance_issue_unique : false
"pid": 2368, "tid": 2368, "ts": 25819ns : performance_issue_same : false
"pid": 2368, "tid": 2368, "ts": 25819ns : performance_issue_same_index : 0
"pid": 2368, "tid": 2368, "ts": 25819ns : performance_sample_count : 256
"pid": 2368, "tid": 2368, "ts": 27418ns : 
"pid": 2368, "tid": 2368, "ts": 27418ns : Requested Settings:
"pid": 2368, "tid": 2368, "ts": 27418ns : Scenario : Offline
"pid": 2368, "tid": 2368, "ts": 27418ns : Test mode : Performance
"pid": 2368, "tid": 2368, "ts": 27418ns : offline_expected_qps : 7463
"pid": 2368, "tid": 2368, "ts": 27418ns : min_duration_ms : 60000
"pid": 2368, "tid": 2368, "ts": 27418ns : max_duration_ms : 0
"pid": 2368, "tid": 2368, "ts": 27418ns : min_query_count : 1
"pid": 2368, "tid": 2368, "ts": 27418ns : max_query_count : 0
"pid": 2368, "tid": 2368, "ts": 27418ns : qsl_rng_seed : 3133965575612453542
"pid": 2368, "tid": 2368, "ts": 27418ns : sample_index_rng_seed : 665484352860916858
"pid": 2368, "tid": 2368, "ts": 27418ns : schedule_rng_seed : 3622009729038561421
"pid": 2368, "tid": 2368, "ts": 27418ns : accuracy_log_rng_seed : 0
"pid": 2368, "tid": 2368, "ts": 27418ns : accuracy_log_probability : 0
"pid": 2368, "tid": 2368, "ts": 27418ns : print_timestamps : false
"pid": 2368, "tid": 2368, "ts": 27418ns : performance_issue_unique : false
"pid": 2368, "tid": 2368, "ts": 27418ns : performance_issue_same : false
"pid": 2368, "tid": 2368, "ts": 27418ns : performance_issue_same_index : 0
"pid": 2368, "tid": 2368, "ts": 27418ns : performance_sample_count_override : 0
"pid": 2368, "tid": 2368, "ts": 27418ns : 
"pid": 2368, "tid": 2368, "ts": 33107ns : Starting performance mode:
"pid": 2368, "tid": 2368, "ts": 178547ns : Loading QSL : "set" : "[1873,183,1526,701,1720,1110,1423,4759,1487,1163,4702,2782,998,141,2734,2005,309,4626,2571,4925,994,4800,561,3565,242,261,1636,2115,3559,3941,4128,4080,1032,2807,3332,732,1569,4497,4323,1380,2384,4048,654,4001,3923,1287,638,4243,634,1100,3934,3449,4983,78,243,1729,3621,4175,3742,4886,3064,2001,2849,4316,3114,2286,4355,2017,2,1076,1974,166,28,12,1453,2453,1718,2932,859,1854,4701,1540,976,1271,3197,4637,3640,1716,2165,4348,893,3606,3813,3527,2233,2482,80,2348,4321,4242,2365,4996,1436,3482,4584,4342,4864,278,3553,1921,2073,4745,3062,4332,1961,1530,4057,1838,2308,1705,1927,1783,4770,397,1345,3861,3698,2686,4486,2832,907,4503,735,3784,1724,3858,3433,4309,630,1508,3576,673,4253,2775,1275,984,700,750,494,4356,1193,3842,1077,2491,2873,3218,3921,4027,3799,1412,3848,435,3917,593,1440,1334,49,4616,2318,3533,4295,4757,3254,584,234,341,2928,1762,3879,2260,2059,4923,2120,679,13,3699,1266,4326,465,4082,3899,481,1601,351,4913,3885,4907,4311,4905,368,273,3907,3315,2603,3607,887,3993,1954,1659,3880,81,3968,3059,1101,1335,2203,2812,823,3625,3725,1324,965,1162,4418,2911,452,1772,4706,1694,3632,2856,843,2102,3004,3267,4548,1622,3350,4703,697,4113,3287,1685,4624,4965,3529,1658,3439,1030,4476,4051,598,4536,3414,1273,2406]"
"pid": 2368, "tid": 2368, "ts": 410937709ns : GeneratedQueries: "queries" : 1, "samples per query" : 492558, "duration" : 133994
"pid": 2368, "tid": 2368, "ts": 415670072ns : ERROR : Ending early: Ran out of generated queries to issue before the minimum query count and test duration were reached.
"pid": 2368, "tid": 2368, "ts": 415670072ns : Please update the relevant expected latency or target qps in the TestSettings so they are more accurate.
"pid": 2368, "tid": 2368, "ts": 379391947812ns : Log Contention Counters:
"pid": 2368, "tid": 2368, "ts": 379391947812ns : 0 : swap_request_slots_retry_count
"pid": 2368, "tid": 2368, "ts": 379391947812ns : 0 : swap_request_slots_retry_retry_count
"pid": 2368, "tid": 2368, "ts": 379391947812ns : 0 : swap_request_slots_retry_reencounter_count
"pid": 2368, "tid": 2368, "ts": 379391947812ns : 0 : start_reading_entries_retry_count
"pid": 2368, "tid": 2368, "ts": 379391947812ns : 0 : tls_total_log_cas_fail_count
"pid": 2368, "tid": 2368, "ts": 379391947812ns : 0 : tls_total_swap_buffers_slot_retry_count
"pid": 2368, "tid": 2368, "ts": 379391951138ns : POWER_BEGIN: "mode" : Performance, "time" : 08-27-2020 02:29:31.568
"pid": 2368, "tid": 2368, "ts": 379391951138ns : POWER_END: "mode" : Performance, "time" : 08-27-2020 02:35:50.542

I don’t know what is the problem.
Thanks

**Comment by jimmy135769** [comment]
Hi all,
I solved the problem, the problem is Server not match T4 and it limits T4 performance. So I change another Server to use.

thanks all :)

**Comment by nvpohanh** [comment]
@jimmy135769 Can we close this issue if the problem has been solved? Thanks
